name: CI/CD

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        shell: cmd
        run: npm ci

      - name: Build
        shell: cmd
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: dist
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Package
        shell: pwsh
        run: Compress-Archive -Path dist/* -DestinationPath dist.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: dist.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          target: ${{ vars.DEPLOYMENT_DIRECTORY }}
          script_before: rm -r ${{ vars.DEPLOYMENT_DIRECTORY }}/*
          script_before_required: true
